services:
  api:
    image: api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
    depends_on:
      - eshopdb
    ports:
      - "5000:8080"
      - "5050:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
  eshopdb:
    image: postgres
    platform: linux
volumes:
  postgres_eshopdb:
